# Proxy / Bastion Server
[proxyserver]
54.198.62.31 ansible_user=ec2-user ansible_ssh_private_key_file=/home/ec2-user/global_key_v2.pem


# Application Server
[appserver]
10.0.19.191 ansible_user=ec2-user ansible_ssh_private_key_file=/home/ec2-user/global_key_v2.pem 

# Database Server
[dbserver]
10.0.47.169 ansible_user=ec2-user ansible_ssh_private_key_file=/home/ec2-user/global_key_v2.pem ansible_python_interpreter=/usr/bin/python3

# Grouping private servers
[private:children]
appserver
dbserver

# SSH through Proxy (Bastion)
[private:vars]
ansible_ssh_common_args=-o ProxyCommand="ssh -i /home/ec2-user/global_key_v2.pem -W %h:%p ec2-user@54.198.62.31"

# All global 
[all:vars]
public_ip=10.0.19.191
db_server_public_ip=10.0.47.169
